# Generated by Django 3.2.13 on 2022-05-24 01:00

import app.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='轮播图名称')),
                ('img', models.ImageField(storage=app.storage.ImageStorage(), upload_to='banner', verbose_name='轮播图')),
                ('bananer_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('banner_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', to_field='name', verbose_name='分类')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('note', models.CharField(max_length=100, verbose_name='文章简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('img', models.ImageField(storage=app.storage.ImageStorage(), upload_to='article', verbose_name='文章图片')),
                ('article_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('article_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', to_field='name', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
